services:
  laravel.test:
    build:
      context: ./docker/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
      - ${MEDIA_PATH-./storage/framework/testing/disks/media}:/mnt/media
    networks:
      - laratunes
    depends_on:
      - olaf
      - redis
  olaf:
    build:
      context: ./Olaf
      dockerfile: ../docker/olaf/Dockerfile
    environment:
      - OLAF_TIMEOUT=${OLAF_TIMEOUT:-120}
    command:
      - php
      - '-S'
      - '0.0.0.0:5000'
      - '-t'
      - /var/www/html
    ports:
      - '5000:5000'
    volumes:
      - './.olaf/docker_dbs:/root/.olaf'
      - './docker/olaf/scripts:/var/www/html'
      - ${MEDIA_PATH-./storage/framework/testing/disks/media}:/root/audio
    networks:
      - laratunes
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'laratunes-redis:/data'
    networks:
      - laratunes
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  rtmp-sink:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-sink
    ports:
      - "1935:1935"
    networks:
      - laratunes
networks:
  laratunes:
    driver: bridge
volumes:
  laratunes-redis:
    driver: local
